apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tf-api
  template:
    metadata:
      labels:
        app: tf-api
    spec:
      containers:
        - name: api
          image: ticketforge-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: tf-config
          env:
            - name: PORT
              value: "3001"
            # Secrets
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: DATABASE_URL
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: JWT_REFRESH_SECRET
            - name: JWT_ACCESS_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: JWT_ACCESS_EXPIRY
            - name: JWT_REFRESH_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: JWT_REFRESH_EXPIRY
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: CLOUDINARY_API_SECRET
            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: RAZORPAY_KEY_ID
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: tf-secrets
                  key: RAZORPAY_KEY_SECRET
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tf-api
spec:
  selector:
    app: tf-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
