apiVersion: v1
kind: ConfigMap
metadata:
  name: tf-config
data:
  NODE_ENV: "production"
  KAFKA_BROKER: "tf-kafka:9092"
  REDIS_URL: "redis://tf-redis:6379"
  # Internal URL fof Next.js SSR to talk to API
  API_URL_INTERNAL: "http://tf-api:3001/graphql"
  # Public URL for Browser to talk to API (Localhost for local K8s)
  NEXT_PUBLIC_API_URL: "http://localhost:3001/graphql"
