apiVersion: v1
kind: Secret
metadata:
  name: tf-secrets
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_USER: amF0aW4= # jatin
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
  POSTGRES_DB: dGlja2V0Zm9yZ2U= # ticketforge
  # postgres://jatin:password@tf-postgres:5432/ticketforge
  DATABASE_URL: cG9zdGdyZXM6Ly9qYXRpbjpwYXNzd29yZEB0Zi1wb3N0Z3Jlczo1NDMyL3RpY2tldGZvcmdl
  JWT_ACCESS_SECRET: c3VwZXJzZWNyZXRfYWNjZXNzX2tleQ==
  JWT_REFRESH_SECRET: c3VwZXJzZWNyZXRfcmVmcmVzaF9rZXk=
  JWT_ACCESS_EXPIRY: MTVt
  JWT_REFRESH_EXPIRY: N2Q=
  CLOUDINARY_CLOUD_NAME: ZHVjY3IyeDl4
  CLOUDINARY_API_KEY: MjM2NTY5NTYzNDk5NTE2
  CLOUDINARY_API_SECRET: NGZUSlJ1bkF5b1Vfa1dMZDNaV0swWE55TnlJ
  RAZORPAY_KEY_ID: cnpwX3Rlc3RfUzdkUnJRY0FZemVnQVA=
  RAZORPAY_KEY_SECRET: bnN2TUdTcWNkNXBFUUFlSGtsVzZMb2RS
